name: Changelog Reminder
on:
  pull_request:
    types:
      - opened
      - ready_for_review

jobs:
  remind:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Changelog Reminder
      uses: peterjgrainger/action-changelog-reminder@v1.3.0
      with:
        changelog_regex: .github/CHANGELOG.md
        customPrMessage: |
          Hello. You may have forgotten to update the changelog!
          Please edit [.github/CHANGELOG.md](/XanaduAI/xanadu-sphinx-theme/blob/master/.github/CHANGELOG.md) with:
          * A one-to-two sentence description of the change. You may include a small working example for new features.
          * A link back to this PR.
          * Your name and GitHub username in the contributors section.
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
