name: Formatting Check
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt

      - name: Run formatters
        run: make format

      - name: Run linters
        run: make lint
